config/routes.rb
Prodiscnews::Application.routes.draw do
  get "about/page"

  get "standings/page"

  resources :teams

  devise_for :users

  get "pages/home"

  resources :posts do
    resources :comments 
  end

  

  root :to => 'pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :author,  :presence => true
  validates :body,  :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :author,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
  validates :content,  :presence => true
  has_many :comments, :dependent => :destroy, :order => "created_at DESC"

end

app/models/team.rb
class Team < ActiveRecord::Base
	validates :name,  :presence => true
  	validates :wins, :numericality => {:greater_than => -1}
  	validates :losses, :numericality => {:greater_than => -1}

	def win_percentage
    	(((self.wins.to_f)/(self.wins.to_f + self.losses.to_f)*100).to_i).to_f/100
  	end 

  	def self.sorted_by_percentage
    	self.all.sort_by(&:win_percentage).reverse
  	end 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

if Rails.env.production?
  	devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
else
	devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable 
end

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def page
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	    @post = Post.find(params[:post_id])
	    @comment = @post.comments.create(params[:comment])
	    redirect_to post_path(@post)
  	end

  	def destroy
	    @post = Post.find(params[:post_id])
	    @comment = @post.comments.find(params[:id])
	    @comment.destroy
	    redirect_to post_path(@post)
  	end	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all(:order => "created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/standings_controller.rb
class StandingsController < ApplicationController
  def page
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController


  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teams }
    end
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    @team = Team.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/new
  # GET /teams/new.json
  def new
    @team = Team.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/1/edit
  def edit
    @team = Team.find(params[:id])
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(params[:team])

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render json: @team, status: :created, location: @team }
      else
        format.html { render action: "new" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teams/1
  # PUT /teams/1.json
  def update
    @team = Team.find(params[:id])

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/standings_helper.rb
module StandingsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/about/page.html.erb
<div class="container">
<h1>About</h1>
<p>This website is the start of a movement to bring information about the American Ultimate Disc League to the general public. This website was developed entirely by Mainak Datta, while all the article content is from John Phillips.</p>
<p>We are still looking to add more and expand this website to truly make it the #1 source of news on the AUDL.</p>
<p>WELCOME TO THE LEAGUE!!!</p>
</div>

app/views/application/_nav.html.erb
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><%= link_to "Pro Disc News", pages_home_path %></li>
              <li><%= link_to "News", posts_path %></li>
              <li><%= link_to "Teams", teams_path %></li>
              <li><%= link_to "Standings", standings_page_path %></li>
              <li><%= link_to "About", about_page_path %></li>
              <li><a href="https://twitter.com/PRODISCNEWS" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @ProDiscNews</a></li>
            </ul>
            </div>
            <div class="nav pull-right">
              <% if user_signed_in? %>
                  Signed in as <%= current_user.email %>. Not you?
                  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
              <% else %>
                  <% if Rails.env.production? %>
                    <%= link_to "Admin Sign In", new_user_session_path %>
                  <% else %>
                    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign In", new_user_session_path %>
                  <% end %>
              <% end %>
            </div>
<!--             Search form -->
            
<!--             <form class="navbar-form pull-right">
              <input class="span2" type="text" placeholder="Search the site">
              <button type="submit" class="btn">Search</button>
            </form> -->
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div> <!-- navbar -->

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>	
  <div class="field">
    <%= f.label :"Display Name" %>
    <%= f.text_field :author, :placeholder => "Enter your name"%>
  </div>
  <div class="field">
    <%= f.label :"Your Comment" %>
    <%= f.text_area :body, :placeholder => "Enter comment", :size => "30x5" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %> 
  </div>
<% end %>

app/views/comments/_show.html.erb
<% @post.comments.each do |comment| %>
  <p>
    <b><%= comment.author %></b>
    on <%= comment.created_at %>
  </p>
  <p>
    <%= comment.body %>
  </p>
  <% if user_signed_in? %>
    <p>
      <%= link_to 'Delete Comment', [comment.post, comment], :confirm => 'Are you sure?', :method => :delete %>
  <% end %>  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prodiscnews</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <%= render partial: 'nav' %>

  </div>
<!--   Devise notification stuff -->
 <% if alert %>
    <div class="alert alert-error">
      <%= alert %>
    </div>
  <% end %>
  <% if notice %>
    <div class="notice notice-error">
      <%= notice %>
    </div>
  <% end %>
<!--   Yield to actual page   -->
  <%= yield %>
</div>
</body>
        <!-- The javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PRO DISC NEWS</title>

  </head>
  <body>
   <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>PRO DISC NEWS</h1>
        <p>THE #1 SOURCE OF NEWS ON THE AMERICAN ULTIMATE DISC LEAGUE!</p>
        <img src="http://prodiscnews.files.wordpress.com/2012/07/history-of-ultimate-frisbee-11.jpeg" class="img-rectangle"/>
      </div>

      <p>by Mainak Datta</p>

    </div> <!-- /container -->
    </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :content, :placeholder => "Enter text here"%>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %> 
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
	<h1>Editing post</h1>
	<%= render 'form' %>
</div>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
    <%= link_to 'Make new Post', new_post_path %>
<% end %>

<% @posts.each do |post| %>
    <div class="container">
        <h1><%= post.title %></h1>
        <p><b>by <%= post.author %></b></p>
        <p><b>Writen on: <%= post.created_at %></b></p>
        <p><%= post.content %></p>
        <td><%= link_to 'Read More', post %></td>
        <!-- make this private -->
        <% if user_signed_in? %>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <% end %>
        <!-- make this private -->
        <% if user_signed_in? %>
            <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
        <% end %>
        <hr size="3" noshade>
    </div>
<% end %>
<!-- </table> -->

<br />

app/views/posts/new.html.erb
<div class="container">
	<h1>New post</h1>
	<%= render 'form' %>
</div>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
	<h1><%= @post.title %></h1>
	<p>
	  <b>by <%= @post.author %></b>
	</p>

	<p>
	  <b>Writen on: <%= @post.created_at %></b>
	</p>

	<p>
	  <%= @post.content %>
	</p>

	<hr size="3" noshade>
	<!-- Display Comments  -->
	<h4>Comments: </h4>
	<%= render "comments/show" %>
	
	<hr size="3" noshade>

	<!-- Add comments -->
	<h4>Add a comment:</h4>
	<%= render "comments/form" %>
 </div>



<% if user_signed_in? %>
	<%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

app/views/standings/page.html.erb
<div class="container">
	<h1>LEAGUE STANDINGS</h1>

	<table class="table">
	  <tr>
	    <td><b>Name</b></td>
	    <td><b>Wins</b></td>
	    <td><b>Losses</b></td>
	    <td><b>Win Pct.</b></td>
	  </tr>
	<% Team.sorted_by_percentage.each do |team| %>
	  <tr>
	    <td><%= team.name %></td>
	    <td><%= team.wins %></td>
	    <td><%= team.losses %></td>
	    <td><%= team.win_percentage %></td>
	  </tr>
	<% end %>
	</table>

</div>